# Generated by Django 3.2.5 on 2021-11-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('make', models.TextField()),
                ('model', models.TextField()),
                ('transmission', models.TextField()),
                ('price', models.FloatField()),
                ('engine', models.TextField()),
                ('colour', models.TextField()),
                ('location', models.TextField()),
                ('availability', models.TextField()),
                ('body_type', models.TextField()),
                ('image', models.URLField()),
                ('fuel', models.TextField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
