# Generated by Django 3.2.5 on 2021-11-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
