# Generated by Django 3.2.5 on 2021-11-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AddField(
            model_name='product',
            name='body_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='engine',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='make',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
