# Generated by Django 3.2.5 on 2021-11-18 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211117_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='model',
            new_name='car_model',
        ),
    ]
